#pragma once
#include <pgmspace.h>

// Serial Controller live monitor UI - embedded in flash (PROGMEM).
//
// Source: Template/src/main/resources/public/index.html (Java reference implementation).
// The HTML is self-contained (all CSS and JS inline, no external assets) and connects
// to ws://<host>/ws/data to drive the live monitor UI.
//
// *** DO NOT EDIT THIS FILE BY HAND ***
// Regenerate from the Java template with:
//   .\generate_index_html.ps1
//
// Java equivalent: Javalin serves index.html as a classpath static resource at GET /.
// On ESP32 it is stored in flash and served via send_P() in Server.cpp handleRoot().
static const char INDEX_HTML[] PROGMEM = R"rawhtml(
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Serial Controller</title>
    <style>
        /* =====================================================================
           Styles are all inline here (no external stylesheet) so the page is a
           single self-contained file - important for serving from an ESP32 or
           similar embedded HTTP server with no filesystem.
           ===================================================================== */
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: 'Segoe UI', system-ui, sans-serif;
            background: #1a1a2e;
            color: #e0e0e0;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            align-items: stretch;
            padding: .75rem 1rem;
        }

        /* Header line: title + badges on one row */
        .header {
            display: flex; align-items: center; gap: .6rem;
            flex-wrap: wrap; margin-bottom: .75rem;
        }
        h1 { font-size: 1.4rem; font-weight: 600; color: #00d4ff; letter-spacing: .5px; }

        /* Status badges (WS connection + device online) */
        .badge {
            display: inline-flex; align-items: center; gap: .4rem;
            padding: .2rem .65rem; border-radius: 999px;
            font-size: .72rem; font-weight: 600;
        }
        .badge .dot { width: 7px; height: 7px; border-radius: 50%; }
        #status.connected      { background: rgba(0,200,83,.15); color: #00c853; }
        #status.connected .dot { background: #00c853; }
        #status.disconnected      { background: rgba(255,82,82,.15); color: #ff5252; }
        #status.disconnected .dot { background: #ff5252; }
        #deviceOnline.online      { background: rgba(0,200,83,.15); color: #00c853; }
        #deviceOnline.online .dot { background: #00c853; }
        #deviceOnline.offline     { background: rgba(255,82,82,.15); color: #ff5252; }
        #deviceOnline.offline .dot{ background: #ff5252; }

        /* WebSocket activity lightning - right-aligned icon in the header.
           Normally dimmed; flashes bright cyan for 250 ms on every WS send/receive. */
        #wsActivity {
            margin-left: auto;
            font-size: 1rem; line-height: 1;
            opacity: .15;
            transition: opacity .05s ease-in;
            user-select: none;
        }
        #wsActivity.active { opacity: 1; }

        /* Shared flex row - cards, toggle row, controls row all use this */
        .row {
            display: flex; gap: .75rem; flex-wrap: wrap;
            margin-bottom: .75rem; width: 100%;
        }

        /* Measurement cards */
        .card {
            background: #16213e; border: 1px solid #0f3460;
            border-radius: 8px; padding: .6rem 1rem; text-align: center;
            flex: 1 1 120px;
        }
        .card .label { font-size: .7rem; text-transform: uppercase; letter-spacing: .8px; color: #7f8fa6; margin-bottom: .15rem; }
        .card .value { font-size: 1.7rem; font-weight: 700; font-variant-numeric: tabular-nums; }
        .card .unit  { font-size: .8rem; color: #7f8fa6; }
        #voltageCard .value { color: #00d4ff; }
        #currentCard .value { color: #ffc107; }
        #powerCard   .value { color: #c8a2f5; }
        #vinCard     .value { color: #7ecb9e; }

        /* Row-2 panels: toggle buttons + info cards - all same flex basis */
        .toggle-panel, .info-panel {
            background: #16213e; border: 1px solid #0f3460; border-radius: 8px;
            padding: .5rem .75rem; text-align: center; flex: 1 1 120px;
            display: flex; flex-direction: column; align-items: center; gap: .35rem;
        }
        .toggle-panel .label, .info-panel .label {
            font-size: .7rem; text-transform: uppercase; letter-spacing: .8px; color: #7f8fa6;
        }
        /* Info panel: two-column table inside */
        .info-panel table { border-collapse: collapse; width: 100%; }
        .info-panel td { padding: .15rem .3rem; font-size: .8rem; text-align: left; }
        .info-panel td:first-child { color: #7f8fa6; font-size: .7rem; text-transform: uppercase; letter-spacing: .5px; width: 55%; }
        .info-panel td:last-child { font-weight: 600; }
        .toggle-btn {
            padding: .35rem 1rem; border-radius: 6px; border: 2px solid #0f3460;
            background: #1a1a2e; color: #e0e0e0; font-size: .85rem; font-weight: 700;
            cursor: pointer; transition: background .15s, border-color .15s; width: 100%;
        }
        .toggle-btn.on  { background: rgba(0,200,83,.2);  border-color: #00c853; color: #00c853; }
        .toggle-btn.off { background: rgba(255,82,82,.15); border-color: #ff5252; color: #ff5252; }
        .toggle-btn:disabled { opacity: .35; cursor: not-allowed; }

        /* Control panels (set voltage / set current) */
        .control-panel {
            background: #16213e; border: 1px solid #0f3460; border-radius: 8px;
            padding: .6rem .75rem; text-align: center; flex: 1 1 260px;
        }
        .control-panel .label { font-size: .7rem; text-transform: uppercase; letter-spacing: .8px; color: #7f8fa6; margin-bottom: .3rem; }
        .control-panel .readout { font-size: 1.6rem; font-weight: 700; font-variant-numeric: tabular-nums; margin-bottom: .3rem; }
        .control-row { display: flex; align-items: center; gap: .6rem; justify-content: center; }
        .control-btn {
            width: 34px; height: 34px; border: 1px solid #0f3460; border-radius: 6px;
            background: #1a1a2e; font-size: 1.2rem; font-weight: 700; cursor: pointer;
            display: flex; align-items: center; justify-content: center;
            transition: background .15s, border-color .15s; user-select: none;
        }
        .control-btn:hover:not(:disabled) { background: #0f3460; }
        .control-btn:disabled { opacity: .35; cursor: not-allowed; }
        #voltageReadout { color: #00d4ff; }
        #currentReadout { color: #ffc107; }
        #voltagePanel .control-btn { color: #00d4ff; }
        #currentPanel .control-btn { color: #ffc107; }

        /* Numeric entry fields */
        .entry-row { display: flex; align-items: center; gap: .5rem; justify-content: center; margin-top: .35rem; }
        .entry-field {
            width: 90px; padding: .35rem .6rem; border-radius: 6px;
            border: 1px solid #0f3460; background: #0f0f23; color: #e0e0e0;
            font-size: .95rem; font-variant-numeric: tabular-nums; text-align: right;
            outline: none; transition: border-color .15s;
        }
        .entry-field:focus { border-color: #7f8fa6; }
        .entry-field:disabled { opacity: .35; cursor: not-allowed; }
        #voltageEntry:focus { border-color: #00d4ff; }
        #currentEntry:focus { border-color: #ffc107; }
        .entry-hint { font-size: .72rem; color: #7f8fa6; }

        /* Sliders */
        .slider-wrap { position: relative; flex: 1; min-width: 80px; display: flex; align-items: center; }
        .slider-wrap canvas { position: absolute; left: 0; top: 0; width: 100%; height: 100%; pointer-events: none; }
        input[type=range] {
            -webkit-appearance: none; appearance: none;
            width: 100%; height: 5px; border-radius: 3px; background: transparent; outline: none;
            position: relative; z-index: 1;
        }
        input[type=range]::-webkit-slider-thumb {
            -webkit-appearance: none; appearance: none;
            width: 20px; height: 20px; border-radius: 50%; cursor: pointer; border: 2px solid #16213e;
        }
        #voltageSlider::-webkit-slider-thumb { background: #00d4ff; box-shadow: 0 0 6px rgba(0,212,255,.4); }
        #currentSlider::-webkit-slider-thumb { background: #ffc107; box-shadow: 0 0 6px rgba(255,193,7,.4); }
        #voltageSlider::-moz-range-thumb { width:20px;height:20px;border-radius:50%;background:#00d4ff;cursor:pointer;border:2px solid #16213e; }
        #currentSlider::-moz-range-thumb { width:20px;height:20px;border-radius:50%;background:#ffc107;cursor:pointer;border:2px solid #16213e; }
        input[type=range]:disabled { opacity: .35; }

        .ok   { color: #00c853; }
        .warn { color: #ff5252; }

        /* Message log - collapsible, full width */
        .log-section {
            width: 100%; margin-top: .25rem;
            background: #16213e; border: 1px solid #0f3460; border-radius: 8px;
            overflow: hidden;
        }
        .log-header {
            display: flex; align-items: center; justify-content: space-between;
            padding: .65rem 1rem; cursor: pointer; user-select: none;
        }
        .log-header:hover { background: rgba(255,255,255,.03); }
        .log-title { font-size: .85rem; text-transform: uppercase; letter-spacing: 1px; color: #7f8fa6; }
        .log-chevron {
            font-size: .8rem; color: #7f8fa6; transition: transform .2s;
            display: inline-block; line-height: 1;
        }
        .log-chevron.open { transform: rotate(180deg); }
        #logBody { display: none; border-top: 1px solid #0f3460; padding: .75rem 1rem; }
        #logBody.open { display: block; }
        #log {
            list-style: none; max-height: 200px; overflow-y: auto;
            font-family: 'Consolas', 'Courier New', monospace; font-size: .78rem; line-height: 1.6; color: #a0a0c0;
        }
        #log li { white-space: nowrap; }
    </style>
</head>
<body>

    <div class="header">
        <h1 id="pageTitle">Serial Controller - Live Monitor</h1>
        <div id="status" class="badge disconnected">
            <span class="dot"></span>
            <span id="statusText">Disconnected</span>
        </div>
        <div id="deviceOnline" class="badge offline">
            <span class="dot"></span>
            <span id="deviceOnlineText">Offline</span>
        </div>
        <span id="wsActivity" title="WebSocket activity">⚡</span>
    </div>

    <!-- Row 1: Measured values -->
    <div class="row">
        <div class="card" id="voltageCard">
            <div class="label">Output Voltage</div>
            <div><span class="value" id="voltageOut">-</span> <span class="unit">V</span></div>
        </div>
        <div class="card" id="currentCard">
            <div class="label">Output Current</div>
            <div><span class="value" id="currentOut">-</span> <span class="unit">A</span></div>
        </div>
        <div class="card" id="powerCard">
            <div class="label">Output Power</div>
            <div><span class="value" id="powerOut">-</span> <span class="unit">W</span></div>
        </div>
        <div class="card" id="vinCard">
            <div class="label">Input Voltage</div>
            <div><span class="value" id="voltageIn">-</span> <span class="unit">V</span></div>
        </div>
    </div>

    <!-- Row 2: Output toggle, Keypad toggle, Mode+Protection info, Temp+Keypad info -->
    <div class="row">
        <div class="toggle-panel">
            <div class="label">Output</div>
            <button id="outputBtn" class="toggle-btn" disabled>-</button>
        </div>
        <div class="toggle-panel">
            <div class="label">Keypad Lock</div>
            <button id="keypadBtn" class="toggle-btn" disabled>-</button>
        </div>
        <div class="info-panel">
            <div class="label">Status</div>
            <table>
                <tr><td>Mode</td>       <td id="cvMode">-</td></tr>
                <tr><td>Protection</td> <td id="protectionState">-</td></tr>
            </table>
        </div>
        <div class="info-panel">
            <div class="label">Sensor</div>
            <table>
                <tr><td>Temperature</td> <td id="tempCelsius">-</td></tr>
                <tr><td>Keypad</td>      <td id="keypadLocked">-</td></tr>
            </table>
        </div>
    </div>

    <!-- Row 3: Set Voltage and Set Current side-by-side -->
    <div class="row">
        <div class="control-panel" id="voltagePanel">
            <div class="label">Set Voltage</div>
            <div class="readout"><span id="voltageReadout">-</span> <span style="font-size:1rem;color:#7f8fa6">V</span></div>
            <div class="control-row">
                <button class="control-btn" id="btnVoltDec" title="-0.1 V" disabled>−</button>
                <div class="slider-wrap">
                    <canvas id="voltageTickCanvas"></canvas>
                    <input type="range" id="voltageSlider" min="0" max="60" step="0.1" value="0" disabled>
                </div>
                <button class="control-btn" id="btnVoltInc" title="+0.1 V" disabled>+</button>
            </div>
            <div class="entry-row">
                <input type="number" id="voltageEntry" class="entry-field" min="0" max="60" step="0.01"
                       placeholder="V" title="Type a voltage and press Enter" disabled>
                <span class="entry-hint">V - press Enter</span>
            </div>
        </div>

        <div class="control-panel" id="currentPanel">
            <div class="label">Set Current</div>
            <div class="readout"><span id="currentReadout">-</span> <span style="font-size:1rem;color:#7f8fa6">A</span></div>
            <div class="control-row">
                <button class="control-btn" id="btnCurrDec" title="-0.1 A" disabled>−</button>
                <div class="slider-wrap">
                    <canvas id="currentTickCanvas"></canvas>
                    <input type="range" id="currentSlider" min="0" max="20" step="0.1" value="0" disabled>
                </div>
                <button class="control-btn" id="btnCurrInc" title="+0.1 A" disabled>+</button>
            </div>
            <div class="entry-row">
                <input type="number" id="currentEntry" class="entry-field" min="0" max="20" step="0.01"
                       placeholder="A" title="Type a current and press Enter" disabled>
                <span class="entry-hint">A - press Enter</span>
            </div>
        </div>
    </div>

    <!-- Message log - collapsible -->
    <div class="log-section">
        <div class="log-header" id="logToggle">
            <span class="log-title">Message Log</span>
            <span class="log-chevron" id="logChevron">&#9660;</span>
        </div>
        <div id="logBody">
            <ul id="log"></ul>
        </div>
    </div>

    <script>
        /* ---- DOM element references ----
           Cached once at startup; JavaScript uses these to read/write the HTML
           elements without repeatedly querying the document. */
        const pageTitleEl      = document.getElementById('pageTitle');
        const statusEl         = document.getElementById('status');
        const statusText       = document.getElementById('statusText');
        const deviceOnlineEl   = document.getElementById('deviceOnline');
        const deviceOnlineText = document.getElementById('deviceOnlineText');
        const voltageOutEl     = document.getElementById('voltageOut');
        const currentOutEl     = document.getElementById('currentOut');
        const powerOutEl       = document.getElementById('powerOut');
        const voltageInEl      = document.getElementById('voltageIn');
        const cvModeEl         = document.getElementById('cvMode');
        const protectionEl     = document.getElementById('protectionState');
        const tempEl           = document.getElementById('tempCelsius');
        const keypadEl         = document.getElementById('keypadLocked');
        const voltageReadout   = document.getElementById('voltageReadout');
        const voltageSlider    = document.getElementById('voltageSlider');
        const voltageEntry     = document.getElementById('voltageEntry');
        const btnVoltDec       = document.getElementById('btnVoltDec');
        const btnVoltInc       = document.getElementById('btnVoltInc');
        const currentReadout   = document.getElementById('currentReadout');
        const currentSlider    = document.getElementById('currentSlider');
        const currentEntry     = document.getElementById('currentEntry');
        const btnCurrDec       = document.getElementById('btnCurrDec');
        const btnCurrInc       = document.getElementById('btnCurrInc');
        const outputBtn        = document.getElementById('outputBtn');
        const keypadBtn        = document.getElementById('keypadBtn');
        const logEl            = document.getElementById('log');

        const wsActivityEl     = document.getElementById('wsActivity');
        let   wsActivityTimer  = null;

        /* Flash the activity dot for 250 ms - called on every WS send and receive. */
        function flashActivity() {
            wsActivityEl.classList.add('active');
            clearTimeout(wsActivityTimer);
            wsActivityTimer = setTimeout(function () { wsActivityEl.classList.remove('active'); }, 250);
        }

        const MAX_LOG        = 20;
        const STEP           = 0.1;

        /* ---- Setpoint interaction timing constants ---- */
        const DEBOUNCE_MS    = 300;   /* trailing-edge delay before a WS write is sent */
        const PENDING_HOLD_MS = 3000; /* hold off server broadcasts after a user write   */
        const HOLD_DELAY_MS  = 400;   /* ms before press-and-hold auto-repeat starts     */
        const HOLD_REPEAT_MS = 150;   /* ms between auto-repeat steps                    */

        /* ---- Topology constants (must match ConverterTopology enum names) ---- */
        const TOPOLOGY_BUCK       = 'BUCK';
        const TOPOLOGY_BOOST      = 'BOOST';
        const TOPOLOGY_BUCK_BOOST = 'BUCK_BOOST';

        /* ---- Tick canvas refs ---- */
        const voltageTickCanvas = document.getElementById('voltageTickCanvas');
        const currentTickCanvas = document.getElementById('currentTickCanvas');

        /* ---- Shared state (mirrors last received ConverterState) ---- */
        let voltageSetting         = 0;
        let currentSetting         = 0;
        let outputEnabled          = false;
        let keypadLocked           = false;
        let limitsApplied          = false;
        let converterTopology      = TOPOLOGY_BUCK_BOOST;  /* updated from first WS message */
        let lastVoltageIn          = null;                 /* last received voltageIn value */
        let staticMaxVoltage       = 60;                   /* maxVoltage from properties (never changes) */
        let staticMaxCurrent       = 20;                   /* maxCurrent from properties (never changes) */
        let configMaxVoltage       = 0;                    /* operator cap (0 = not configured) */
        let configMaxCurrent       = 0;                    /* operator cap (0 = not configured) */

        /* ---- Setpoint pending-write guard ---- */
        /* Set to Date.now() + PENDING_HOLD_MS whenever the user changes a setpoint.     */
        /* While Date.now() < *PendingUntil the WS broadcast is not allowed to overwrite */
        /* the locally-displayed value, preventing transient device read-backs flipping  */
        /* the display back to an intermediate value.                                    */
        let voltagePendingUntil    = 0;
        let currentPendingUntil    = 0;

        /* ---- Debounce / press-and-hold timers ---- */
        let voltageDebounceTimer   = null;
        let currentDebounceTimer   = null;
        let voltageRepeatTimeout   = null;
        let currentRepeatTimeout   = null;
        let voltageRepeatInterval  = null;
        let currentRepeatInterval  = null;

        /* ---- Previous state for change-detection logging ---- */
        let loggedVoltageSet    = null;   /* last voltageSet logged from server push  */
        let loggedCurrentSet    = null;   /* last currentSet logged from server push  */
        let loggedOutputEnabled = null;   /* last outputEnabled state logged           */
        let loggedKeypadLocked  = null;   /* last keypadLocked state logged            */
        let loggedProtection    = null;   /* last protectionState logged               */
        let loggedOnline        = null;   /* last deviceOnline state logged            */

        /* ---- Slider drag flags ---- */
        /* voltageDragging / currentDragging: true from pointerdown until the 'change' event  */
        /* that follows pointerup has been processed. While true, updateVoltageUI /           */
        /* updateCurrentUI must not write the slider element - that would fight the browser's */
        /* own drag tracking. The flag is cleared inside 'change', not in 'pointerup', so    */
        /* the change handler can use it to detect that pointerup already sent the value.    */
        let voltageDragging        = false;
        let currentDragging        = false;

        /* ---- Slider tick marks ---- */
        /**
         * Draws integer-step tick marks on a canvas overlaid behind a range slider.
         *
         * @param {HTMLCanvasElement} canvas
         * @param {number} min          slider minimum
         * @param {number} max          slider maximum (full device range)
         * @param {number|null} vinLimit    amber Vin−1V marker position, or null
         * @param {number|null} configLimit red operator-cap marker position, or null
         */
        function drawTicks(canvas, min, max, vinLimit, configLimit) {
            var wrap = canvas.parentElement;
            var dpr  = window.devicePixelRatio || 1;
            var w    = wrap.clientWidth;
            var h    = wrap.clientHeight || 24;
            if (w === 0) return;
            canvas.width  = w * dpr;
            canvas.height = h * dpr;
            var ctx = canvas.getContext('2d');
            ctx.scale(dpr, dpr);
            ctx.clearRect(0, 0, w, h);

            /* The native range slider track does not occupy the full element width -
               the thumb is centred at the track ends, so usable track is inset by
               half a thumb-width (10 px) on each side. */
            var PAD  = 10;
            var span = w - 2 * PAD;
            var mid  = h / 2;
            var range = max - min;

            /* Draw the track background so it remains visible under the canvas */
            ctx.beginPath();
            ctx.roundRect(PAD, mid - 2.5, span, 5, 3);
            ctx.fillStyle = '#0f3460';
            ctx.fill();

            /* Integer tick marks */
            for (var v = Math.ceil(min); v <= max; v++) {
                var x = PAD + (v - min) / range * span;
                ctx.beginPath();
                ctx.moveTo(x, mid - 7);
                ctx.lineTo(x, mid + 7);
                ctx.strokeStyle = 'rgba(255,255,255,0.18)';
                ctx.lineWidth = 1;
                ctx.stroke();
            }

            /* Vin − 1 V marker (amber, only for buck converters) */
            if (vinLimit !== null && vinLimit !== undefined && isFinite(vinLimit)
                    && vinLimit >= min && vinLimit <= max) {
                var xv = PAD + (vinLimit - min) / range * span;
                ctx.beginPath();
                ctx.moveTo(xv, mid - 9);
                ctx.lineTo(xv, mid + 9);
                ctx.strokeStyle = '#ffa000';
                ctx.lineWidth = 2;
                ctx.stroke();
            }

            /* Operator config-cap marker (red) */
            if (configLimit !== null && configLimit !== undefined && isFinite(configLimit)
                    && configLimit >= min && configLimit <= max) {
                var xc = PAD + (configLimit - min) / range * span;
                ctx.beginPath();
                ctx.moveTo(xc, mid - 9);
                ctx.lineTo(xc, mid + 9);
                ctx.strokeStyle = '#e53935';
                ctx.lineWidth = 2;
                ctx.stroke();
            }
        }

        /* Returns the Buck voltage ceiling (Vin − 1 V), or null if not applicable. */
        function buckCeiling() {
            if (converterTopology === TOPOLOGY_BUCK && lastVoltageIn !== null) {
                return Math.min(staticMaxVoltage, lastVoltageIn - 1);
            }
            return null;
        }

        /**
         * Returns the effective voltage ceiling: tightest of buckCeiling and configMaxVoltage.
         * Falls back to staticMaxVoltage when neither applies.
         */
        function effectiveVoltageMax() {
            var ceil = buckCeiling();
            var base = (ceil !== null) ? ceil : staticMaxVoltage;
            return (configMaxVoltage > 0) ? Math.min(base, configMaxVoltage) : base;
        }

        /**
         * Returns the effective current ceiling: configMaxCurrent when configured and tighter,
         * otherwise the device hard limit.
         */
        function effectiveCurrentMax() {
            return (configMaxCurrent > 0) ? Math.min(staticMaxCurrent, configMaxCurrent) : staticMaxCurrent;
        }

        /**
         * Enforces the effective voltage ceiling on the entry field and snaps the current
         * setpoint if it is above the new ceiling.  Called whenever Vin, topology, or
         * configMaxVoltage changes.
         */
        function applyVoltageCeiling() {
            if (!limitsApplied) { return; }
            var effectiveMax = effectiveVoltageMax();
            voltageEntry.max  = effectiveMax;
            if (voltageSetting > effectiveMax) {
                voltageSetting = +effectiveMax.toFixed(2);
                updateVoltageUI();
            }
            redrawVoltageTicks();
        }

        /**
         * Enforces the effective current ceiling on the entry field and snaps the current
         * setpoint if it is above the new ceiling.  Called whenever configMaxCurrent changes
         * or device limits are first applied.
         */
        function applyCurrentCeiling() {
            if (!limitsApplied) { return; }
            var effectiveMax = effectiveCurrentMax();
            currentEntry.max = effectiveMax;
            if (currentSetting > effectiveMax) {
                currentSetting = +effectiveMax.toFixed(2);
                updateCurrentUI();
            }
            redrawCurrentTicks();
        }

        function redrawVoltageTicks() {
            var min = parseFloat(voltageSlider.min);
            var max = staticMaxVoltage;
            var vinLimit    = (converterTopology === TOPOLOGY_BUCK && lastVoltageIn !== null)
                               ? (lastVoltageIn - 1) : null;
            var configLimit = (configMaxVoltage > 0) ? configMaxVoltage : null;
            drawTicks(voltageTickCanvas, min, max, vinLimit, configLimit);
        }

        function redrawCurrentTicks() {
            var min = parseFloat(currentSlider.min);
            var max = staticMaxCurrent;
            var configLimit = (configMaxCurrent > 0) ? configMaxCurrent : null;
            drawTicks(currentTickCanvas, min, max, null, configLimit);
        }

        /* Redraw on window resize */
        window.addEventListener('resize', function () {
            redrawVoltageTicks();
            redrawCurrentTicks();
        });

        /* ---- Protection code → human-readable label ----
           Maps the integer protectionState field from ConverterState to the short
           label shown in the Status panel.
           0=OK (no fault), 1=OVP (over-voltage), 2=OCP (over-current),
           3=OPP (over-power), 4=LVP (low-voltage input), 5=OAH (amp-hour limit),
           6=OHP (over-heat/power), 7=OTP (over-temperature). */
        const PROT = { 0:'OK', 1:'OVP', 2:'OCP', 3:'OPP', 4:'LVP', 5:'OAH', 6:'OHP', 7:'OTP' };
        function protLabel(code) { return PROT[code] !== undefined ? PROT[code] : 'ERR ' + code; }

        /* ---- Log toggle ---- */
        document.getElementById('logToggle').addEventListener('click', function () {
            var body    = document.getElementById('logBody');
            var chevron = document.getElementById('logChevron');
            var open    = body.classList.toggle('open');
            chevron.classList.toggle('open', open);
        });

        /* ---- Control helpers ---- */
        function setControlsEnabled(on) {
            voltageSlider.disabled = !on;
            voltageEntry.disabled  = !on;
            btnVoltDec.disabled    = !on;
            btnVoltInc.disabled    = !on;
            currentSlider.disabled = !on;
            currentEntry.disabled  = !on;
            btnCurrDec.disabled    = !on;
            btnCurrInc.disabled    = !on;
            outputBtn.disabled     = !on;
            keypadBtn.disabled     = !on;
        }

        function updateVoltageUI() {
            voltageReadout.textContent = voltageSetting.toFixed(2);
            if (!voltageDragging) { voltageSlider.value = voltageSetting; }
            if (document.activeElement !== voltageEntry) {
                voltageEntry.value = voltageSetting.toFixed(2);
            }
        }

        function updateCurrentUI() {
            currentReadout.textContent = currentSetting.toFixed(2);
            if (!currentDragging) { currentSlider.value = currentSetting; }
            if (document.activeElement !== currentEntry) {
                currentEntry.value = currentSetting.toFixed(2);
            }
        }

        function updateOutputUI() {
            if (outputEnabled) {
                outputBtn.textContent = 'On';
                outputBtn.className = 'toggle-btn on';
            } else {
                outputBtn.textContent = 'Off';
                outputBtn.className = 'toggle-btn off';
            }
        }

        function updateKeypadUI() {
            if (keypadLocked) {
                keypadBtn.textContent = 'Locked';
                keypadBtn.className = 'toggle-btn on';
            } else {
                keypadBtn.textContent = 'Unlocked';
                keypadBtn.className = 'toggle-btn off';
            }
        }

        /* ---- Send helpers ---- */
        function sendVoltage() {
            if (ws && ws.readyState === WebSocket.OPEN) {
                flashActivity();
                ws.send(JSON.stringify({ setVoltage: voltageSetting }));
                loggedVoltageSet = Math.round(voltageSetting * 100) / 100;
                addLog('⚡ Set voltage → ' + voltageSetting.toFixed(2) + ' V');
            }
        }

        function sendCurrent() {
            if (ws && ws.readyState === WebSocket.OPEN) {
                flashActivity();
                ws.send(JSON.stringify({ setCurrent: currentSetting }));
                loggedCurrentSet = Math.round(currentSetting * 100) / 100;
                addLog('⚡ Set current → ' + currentSetting.toFixed(2) + ' A');
            }
        }

        /* Schedule a debounced voltage send - resets the timer on every call so only the
           final value in a rapid burst (slider drag, repeated button clicks) is transmitted.
           The pending guard is stamped HERE, immediately, so the WS broadcast cannot overwrite
           the locally-displayed value during the debounce window. */
        function scheduleVoltageSend() {
            voltagePendingUntil = Date.now() + PENDING_HOLD_MS;
            clearTimeout(voltageDebounceTimer);
            voltageDebounceTimer = setTimeout(sendVoltage, DEBOUNCE_MS);
        }

        /* Schedule a debounced current send. */
        function scheduleCurrentSend() {
            currentPendingUntil = Date.now() + PENDING_HOLD_MS;
            clearTimeout(currentDebounceTimer);
            currentDebounceTimer = setTimeout(sendCurrent, DEBOUNCE_MS);
        }

        /* Stop voltage press-and-hold auto-repeat and send the final value once. */
        function cancelVoltageRepeat() {
            clearTimeout(voltageRepeatTimeout);
            clearInterval(voltageRepeatInterval);
            voltageRepeatTimeout  = null;
            if (voltageRepeatInterval !== null) {
                /* Interval was running - send the final stepped value now. */
                voltagePendingUntil = Date.now() + PENDING_HOLD_MS;
                sendVoltage();
            }
            voltageRepeatInterval = null;
        }

        /* Stop current press-and-hold auto-repeat and send the final value once. */
        function cancelCurrentRepeat() {
            clearTimeout(currentRepeatTimeout);
            clearInterval(currentRepeatInterval);
            currentRepeatTimeout  = null;
            if (currentRepeatInterval !== null) {
                currentPendingUntil = Date.now() + PENDING_HOLD_MS;
                sendCurrent();
            }
            currentRepeatInterval = null;
        }

        /* ---- Voltage controls ---- */

        /* Drag start - set flag so updateVoltageUI does not fight the browser thumb position. */
        voltageSlider.addEventListener('pointerdown', function () {
            voltageDragging = true;
            voltagePendingUntil = Date.now() + PENDING_HOLD_MS;
        });

        /* Live-track slider position while dragging: update display only, never send. */
        voltageSlider.addEventListener('input', function () {
            var v = parseFloat(voltageSlider.value);
            var eMax = effectiveVoltageMax();
            voltageSetting = (v > eMax) ? +eMax.toFixed(2) : +v.toFixed(2);
            voltagePendingUntil = Date.now() + PENDING_HOLD_MS;
            updateVoltageUI();
        });

        /* Release - send the final value. Keep voltageDragging=true so the 'change' event
           that the browser fires immediately after pointerup knows not to send again. */
        voltageSlider.addEventListener('pointerup', function () {
            var v = parseFloat(voltageSlider.value);
            var eMax = effectiveVoltageMax();
            voltageSetting = (v > eMax) ? +eMax.toFixed(2) : +v.toFixed(2);
            updateVoltageUI();
            voltagePendingUntil = Date.now() + PENDING_HOLD_MS;
            sendVoltage();
            /* voltageDragging cleared in 'change' below */
        });

        /* 'change' fires after every pointer release AND after keyboard steps.
           If voltageDragging is true, pointerup already sent - just clear the flag.
           Otherwise (keyboard step while slider is focused) schedule a debounced send. */
        voltageSlider.addEventListener('change', function () {
            if (voltageDragging) {
                voltageDragging = false;   /* end of pointer-drag cycle */
                return;
            }
            var v    = parseFloat(voltageSlider.value);
            var eMax = effectiveVoltageMax();
            if (v > eMax) {
                /* Snap thumb back to ceiling - do not send the over-limit value. */
                voltageSetting = +eMax.toFixed(2);
                updateVoltageUI();
            } else {
                voltageSetting = +v.toFixed(2);
                updateVoltageUI();
                scheduleVoltageSend();
            }
        });

        btnVoltDec.addEventListener('click', function () {
            voltageSetting = Math.max(parseFloat(voltageSlider.min), +(voltageSetting - STEP).toFixed(2));
            updateVoltageUI(); scheduleVoltageSend();
        });
        btnVoltInc.addEventListener('click', function () {
            voltageSetting = Math.min(effectiveVoltageMax(), +(voltageSetting + STEP).toFixed(2));
            updateVoltageUI(); scheduleVoltageSend();
        });

        /* Press-and-hold auto-repeat for voltage decrement button.
           The interval only updates the display; cancelVoltageRepeat sends the single final value. */
        btnVoltDec.addEventListener('pointerdown', function () {
            voltageRepeatTimeout = setTimeout(function () {
                voltageRepeatInterval = setInterval(function () {
                    voltageSetting = Math.max(parseFloat(voltageSlider.min), +(voltageSetting - STEP).toFixed(2));
                    voltagePendingUntil = Date.now() + PENDING_HOLD_MS;
                    updateVoltageUI();
                }, HOLD_REPEAT_MS);
            }, HOLD_DELAY_MS);
        });
        btnVoltDec.addEventListener('pointerup',    cancelVoltageRepeat);
        btnVoltDec.addEventListener('pointerleave', cancelVoltageRepeat);

        /* Press-and-hold auto-repeat for voltage increment button. */
        btnVoltInc.addEventListener('pointerdown', function () {
            voltageRepeatTimeout = setTimeout(function () {
                voltageRepeatInterval = setInterval(function () {
                    voltageSetting = Math.min(effectiveVoltageMax(), +(voltageSetting + STEP).toFixed(2));
                    voltagePendingUntil = Date.now() + PENDING_HOLD_MS;
                    updateVoltageUI();
                }, HOLD_REPEAT_MS);
            }, HOLD_DELAY_MS);
        });
        btnVoltInc.addEventListener('pointerup',    cancelVoltageRepeat);
        btnVoltInc.addEventListener('pointerleave', cancelVoltageRepeat);

        voltageEntry.addEventListener('keydown', function (e) {
            if (e.key === 'Enter') {
                var v    = parseFloat(voltageEntry.value);
                var eMax = effectiveVoltageMax();
                if (!isNaN(v) && v <= eMax && v >= parseFloat(voltageSlider.min)) {
                    voltageSetting = +v.toFixed(2);
                    updateVoltageUI();
                    voltagePendingUntil = Date.now() + PENDING_HOLD_MS;
                    sendVoltage();  /* entry field: send immediately, no debounce */
                } else {
                    /* Invalid or over-ceiling - reset field to last accepted value. */
                    voltageEntry.value = voltageSetting.toFixed(2);
                }
                voltageEntry.blur();
            }
        });

        /* ---- Current controls ---- */

        /* Drag start. */
        currentSlider.addEventListener('pointerdown', function () {
            currentDragging = true;
            currentPendingUntil = Date.now() + PENDING_HOLD_MS;
        });

        /* Live-track slider position while dragging. */
        currentSlider.addEventListener('input', function () {
            var v    = parseFloat(currentSlider.value);
            var eMax = effectiveCurrentMax();
            currentSetting = (v > eMax) ? +eMax.toFixed(2) : +v.toFixed(2);
            currentPendingUntil = Date.now() + PENDING_HOLD_MS;
            updateCurrentUI();
        });

        /* Release - send the final value; keep currentDragging=true for the 'change' guard. */
        currentSlider.addEventListener('pointerup', function () {
            var v    = parseFloat(currentSlider.value);
            var eMax = effectiveCurrentMax();
            currentSetting = (v > eMax) ? +eMax.toFixed(2) : +v.toFixed(2);
            updateCurrentUI();
            currentPendingUntil = Date.now() + PENDING_HOLD_MS;
            sendCurrent();
            /* currentDragging cleared in 'change' below */
        });

        /* 'change' fires after pointer release and keyboard steps. */
        currentSlider.addEventListener('change', function () {
            if (currentDragging) {
                currentDragging = false;   /* end of pointer-drag cycle */
                return;
            }
            var v    = parseFloat(currentSlider.value);
            var eMax = effectiveCurrentMax();
            if (v > eMax) {
                currentSetting = +eMax.toFixed(2);
                updateCurrentUI();
            } else {
                currentSetting = +v.toFixed(2);
                updateCurrentUI();
                scheduleCurrentSend();
            }
        });

        btnCurrDec.addEventListener('click', function () {
            currentSetting = Math.max(parseFloat(currentSlider.min), +(currentSetting - STEP).toFixed(2));
            updateCurrentUI(); scheduleCurrentSend();
        });
        btnCurrInc.addEventListener('click', function () {
            currentSetting = Math.min(effectiveCurrentMax(), +(currentSetting + STEP).toFixed(2));
            updateCurrentUI(); scheduleCurrentSend();
        });

        /* Press-and-hold auto-repeat for current decrement button.
           The interval only updates the display; cancelCurrentRepeat sends the single final value. */
        btnCurrDec.addEventListener('pointerdown', function () {
            currentRepeatTimeout = setTimeout(function () {
                currentRepeatInterval = setInterval(function () {
                    currentSetting = Math.max(parseFloat(currentSlider.min), +(currentSetting - STEP).toFixed(2));
                    currentPendingUntil = Date.now() + PENDING_HOLD_MS;
                    updateCurrentUI();
                }, HOLD_REPEAT_MS);
            }, HOLD_DELAY_MS);
        });
        btnCurrDec.addEventListener('pointerup',    cancelCurrentRepeat);
        btnCurrDec.addEventListener('pointerleave', cancelCurrentRepeat);

        /* Press-and-hold auto-repeat for current increment button. */
        btnCurrInc.addEventListener('pointerdown', function () {
            currentRepeatTimeout = setTimeout(function () {
                currentRepeatInterval = setInterval(function () {
                    currentSetting = Math.min(effectiveCurrentMax(), +(currentSetting + STEP).toFixed(2));
                    currentPendingUntil = Date.now() + PENDING_HOLD_MS;
                    updateCurrentUI();
                }, HOLD_REPEAT_MS);
            }, HOLD_DELAY_MS);
        });
        btnCurrInc.addEventListener('pointerup',    cancelCurrentRepeat);
        btnCurrInc.addEventListener('pointerleave', cancelCurrentRepeat);

        currentEntry.addEventListener('keydown', function (e) {
            if (e.key === 'Enter') {
                var v = parseFloat(currentEntry.value);
                if (!isNaN(v)) {
                    currentSetting = Math.min(effectiveCurrentMax(),
                                     Math.max(parseFloat(currentSlider.min), +v.toFixed(2)));
                    updateCurrentUI();
                    currentPendingUntil = Date.now() + PENDING_HOLD_MS;
                    sendCurrent();  /* entry field: send immediately, no debounce */
                }
                currentEntry.blur();
            }
        });

        /* ---- Output toggle ---- */
        outputBtn.addEventListener('click', function () {
            if (ws && ws.readyState === WebSocket.OPEN) {
                var next = !outputEnabled;
                flashActivity();
                ws.send(JSON.stringify({ setOutput: next }));
                loggedOutputEnabled = next;
                addLog((next ? '⏽ Set output → ON' : '⏻ Set output → OFF'));
            }
        });

        /* ---- Keypad toggle ---- */
        keypadBtn.addEventListener('click', function () {
            if (ws && ws.readyState === WebSocket.OPEN) {
                var next = !keypadLocked;
                flashActivity();
                ws.send(JSON.stringify({ setKeypad: next }));
                loggedKeypadLocked = next;
                addLog((next ? '🔒 Set keypad → LOCKED' : '🔓 Set keypad → UNLOCKED'));
            }
        });

        /* ---- WebSocket ---- */
        var ws;
        var reconnectDelay = 1000;

        function connect() {
            var wsUrl = 'ws://' + window.location.host + '/ws/data';
            ws = new WebSocket(wsUrl);

            ws.onopen = function () {
                reconnectDelay = 1000;
                statusEl.className = 'badge connected';
                statusText.textContent = 'Connected';
                setControlsEnabled(true);
                addLog('⚡ Connected to ' + wsUrl);
            };

            ws.onmessage = function (event) {
                flashActivity();
                try {
                    var d = JSON.parse(event.data);

                    /* Measured values */
                    if (d.voltageOut         !== undefined) voltageOutEl.textContent = d.voltageOut.toFixed(2);
                    if (d.currentOut         !== undefined) currentOutEl.textContent = d.currentOut.toFixed(2);
                    if (d.powerOut           !== undefined) powerOutEl.textContent   = d.powerOut.toFixed(2);
                    if (d.voltageIn          !== undefined) voltageInEl.textContent  = d.voltageIn.toFixed(2);
                    /* temperatureCelsius < -273: sentinel value used by drivers that have no
                       temperature sensor (e.g. RD50xx returns -999.0); display 'N/A' instead. */
                    if (d.temperatureCelsius !== undefined) tempEl.textContent       = d.temperatureCelsius < -273 ? 'N/A' : d.temperatureCelsius.toFixed(1) + ' °C';
                    if (d.cvMode             !== undefined) cvModeEl.textContent     = d.cvMode ? 'CV' : 'CC';

                    /* Keypad status row (read-only display in table) */
                    if (d.keypadLocked !== undefined) {
                        keypadEl.textContent = d.keypadLocked ? 'Locked' : 'Unlocked';
                    }

                    /* Protection state */
                    if (d.protectionState !== undefined) {
                        var label = protLabel(d.protectionState);
                        protectionEl.textContent = label;
                        protectionEl.className   = (d.protectionState === 0) ? 'ok' : 'warn';
                    }

                    /* Device limits - apply once on first message with valid limits */
                    if (!limitsApplied && d.maxVoltage !== undefined && d.maxVoltage > 0) {
                        staticMaxVoltage   = d.maxVoltage;
                        voltageSlider.min  = d.minVoltage  !== undefined ? d.minVoltage  : 0;
                        voltageSlider.max  = d.maxVoltage;
                        voltageEntry.min   = voltageSlider.min;
                        voltageEntry.max   = voltageSlider.max;
                        staticMaxCurrent   = d.maxCurrent  !== undefined ? d.maxCurrent  : 20;
                        currentSlider.min  = d.minCurrent  !== undefined ? d.minCurrent  : 0;
                        currentSlider.max  = staticMaxCurrent;
                        currentEntry.min   = currentSlider.min;
                        currentEntry.max   = currentSlider.max;
                        /* Apply operator caps from configMaxVoltage/Current already received */
                        limitsApplied = true;
                        applyVoltageCeiling();
                        applyCurrentCeiling();
                    }

                    /* Operator config caps - received once; update ceilings and redraw */
                    if (d.configMaxVoltage !== undefined) {
                        configMaxVoltage = d.configMaxVoltage;
                        applyVoltageCeiling();
                    }
                    if (d.configMaxCurrent !== undefined) {
                        configMaxCurrent = d.configMaxCurrent;
                        applyCurrentCeiling();
                    }

                    /* Topology - determines whether a Vin-derived ceiling applies */
                    if (d.converterTopology !== undefined) {
                        converterTopology = d.converterTopology;
                        applyVoltageCeiling();
                    }

                    /* Device identity - merge into page title */
                    if (d.manufacturer !== undefined && d.deviceName !== undefined
                            && d.manufacturer !== 'Unknown' && d.deviceName !== 'Unknown') {
                        const fwSuffix = (d.firmwareVersion && d.firmwareVersion !== '') ? ' (' + d.firmwareVersion + ')' : '';
                        pageTitleEl.textContent = d.manufacturer + ' ' + d.deviceName + fwSuffix + ' - Live Monitor';
                        document.title = d.manufacturer + ' ' + d.deviceName + fwSuffix;
                    }

                    /* Vin - update amber buck-limit marker and enforce slider ceiling */
                    if (d.voltageIn !== undefined) {
                        lastVoltageIn = d.voltageIn;
                        applyVoltageCeiling();
                    }

                    /* Setpoints - update UI only when no local write is pending.
                       While voltagePendingUntil / currentPendingUntil is in the future the
                       user has recently changed the value and the broadcast must not overwrite
                       it, preventing the transient device read-back flipping the display. */
                    if (d.voltageSet !== undefined && Date.now() >= voltagePendingUntil) {
                        voltageSetting = d.voltageSet;
                        updateVoltageUI();
                    }
                    if (d.currentSet !== undefined && Date.now() >= currentPendingUntil) {
                        currentSetting = d.currentSet;
                        updateCurrentUI();
                    }

                    /* Output state */
                    if (d.outputEnabled !== undefined) {
                        outputEnabled = d.outputEnabled;
                        updateOutputUI();
                    }

                    /* Keypad state (toggle button) */
                    if (d.keypadLocked !== undefined) {
                        keypadLocked = d.keypadLocked;
                        updateKeypadUI();
                    }

                    /* Device online/offline state */
                    if (d.deviceOnline !== undefined) {
                        if (d.deviceOnline) {
                            deviceOnlineEl.className = 'badge online';
                            deviceOnlineText.textContent = 'Online';
                        } else {
                            deviceOnlineEl.className = 'badge offline';
                            deviceOnlineText.textContent = 'Offline';
                        }
                    }

                    /* Log meaningful state changes only - not the raw JSON broadcast */

                    /* Device online / offline transitions */
                    if (d.deviceOnline !== undefined && d.deviceOnline !== loggedOnline) {
                        loggedOnline = d.deviceOnline;
                        addLog(d.deviceOnline ? '✅ Device Online' : '🛑 Device Offline');
                    }

                    /* Protection trips and clears */
                    if (d.protectionState !== undefined && d.protectionState !== loggedProtection) {
                        var prevProtection = loggedProtection;
                        loggedProtection = d.protectionState;
                        if (d.protectionState !== 0) addLog('⚠️ Protection tripped: ' + protLabel(d.protectionState));
                        else if (prevProtection !== null && prevProtection !== 0) addLog('✅ Protection cleared');
                    }

                    /* Output state changes */
                    if (d.outputEnabled !== undefined && d.outputEnabled !== loggedOutputEnabled) {
                        loggedOutputEnabled = d.outputEnabled;
                        addLog(d.outputEnabled ? '⏽ Output ON' : '⏻ Output OFF');
                    }

                    /* Keypad state changes */
                    if (d.keypadLocked !== undefined && d.keypadLocked !== loggedKeypadLocked) {
                        loggedKeypadLocked = d.keypadLocked;
                        addLog((d.keypadLocked ? '🔒 Keypad Locked' : '🔓 Keypad Unlocked'));
                    }

                    /* Setpoints changed externally (device keypad or REST API).
                       Only log when no local write is pending - this avoids echoing our own
                       sends, which arrive back as a server broadcast ~1 s later.
                       The limitsApplied guard suppresses spurious "0.00 V" lines that would
                       otherwise appear on the very first broadcast before device limits have
                       been received and the sliders have been set to their real ranges. */
                    if (d.voltageSet !== undefined && Date.now() >= voltagePendingUntil) {
                        var vRounded = Math.round(d.voltageSet * 100) / 100;
                        if (loggedVoltageSet === null || Math.abs(vRounded - loggedVoltageSet) >= 0.01) {
                            loggedVoltageSet = vRounded;
                            if (limitsApplied) addLog('↩ Voltage set → ' + vRounded.toFixed(2) + ' V (device/API)');
                        }
                    }
                    if (d.currentSet !== undefined && Date.now() >= currentPendingUntil) {
                        var aRounded = Math.round(d.currentSet * 100) / 100;
                        if (loggedCurrentSet === null || Math.abs(aRounded - loggedCurrentSet) >= 0.01) {
                            loggedCurrentSet = aRounded;
                            if (limitsApplied) addLog('↩ Current set → ' + aRounded.toFixed(2) + ' A (device/API)');
                        }
                    }

                } catch (e) {
                    addLog('Non-JSON: ' + event.data);
                }
            };

            ws.onclose = function () {
                statusEl.className = 'badge disconnected';
                statusText.textContent = 'Disconnected';
                setControlsEnabled(false);
                addLog('🔌 Disconnected - reconnecting in ' + (reconnectDelay / 1000) + 's');
                setTimeout(function () {
                    reconnectDelay = Math.min(reconnectDelay * 2, 30000);
                    connect();
                }, reconnectDelay);
            };

            /* On any WebSocket error immediately close - the onclose handler will then
               schedule a reconnect with exponential back-off. */
            ws.onerror = function () { ws.close(); };
        }

        /* Prepends a timestamped entry to the Message Log list (newest at top).
           Trims the list to MAX_LOG entries so the DOM does not grow unbounded. */
        function addLog(msg) {
            var li = document.createElement('li');
            var ts = new Date().toLocaleTimeString();
            li.textContent = ts + '  ' + msg;
            logEl.prepend(li);
            while (logEl.children.length > MAX_LOG) logEl.removeChild(logEl.lastChild);
        }

        connect();
    </script>
</body>
</html>
)rawhtml";