; PlatformIO Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
; Tell PlatformIO to look for source files in the current directory 
; to keep it compatible with the Arduino IDE structure.
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_dir = src       ; Matches Arduino IDE's sketch-local library path (src/<LibName>/)

; Serial Monitor Settings
monitor_speed = 115200

; Library dependencies
lib_deps =
    https://github.com/tzapu/WiFiManager.git#v2.0.17
    bblanchon/ArduinoJson @ ^7.4.3
    ESP32Async/ESPAsyncWebServer @ ^3.12.1
    ESP32Async/AsyncTCP @ ^3.5.0
