; PlatformIO Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
; Tell PlatformIO to look for source files in the current directory 
; to keep it compatible with the Arduino IDE structure.
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor Settings
monitor_speed = 115200

; Library dependencies
lib_deps = 
    https://github.com/tzapu/WiFiManager.git
