<#
.SYNOPSIS
    Converts the Java template index.html into the ESP32 PROGMEM C++ header.

.DESCRIPTION
    Reads  Template/src/main/resources/public/index.html  relative to the
    workspace root and writes the self-contained PROGMEM header to
    SerialController/src/SerialController/src/index_html.h.
    The Java workspace needs to be symlinked to ./Template!

    Run this script whenever the Java UI changes:
        cd <workspace-root>
        .\Generate_index_html.ps1

    The output file is a valid C++ header that embeds the HTML as a C++
    raw string literal (R"rawhtml(...)rawhtml") inside a static PROGMEM
    array.  It is included only from Server.cpp, so the single flash copy
    is correct despite the 'static' storage class.

.NOTES
    The raw string delimiter "rawhtml" must not appear anywhere inside the
    HTML content.  The script verifies this before writing.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ---- Paths (relative to the script's own directory, i.e. the workspace root) ----
$scriptDir = $PSScriptRoot
$htmlSrc   = Join-Path $scriptDir 'Template\src\main\resources\public\index.html'
$headerDst = Join-Path $scriptDir 'SerialController\src\SerialController\src\index_html.h'

# ---- Read source ---------------------------------------------------------------
if (-not (Test-Path $htmlSrc)) {
    Write-Error "Source not found: $htmlSrc"
    exit 1
}
$html = Get-Content -Path $htmlSrc -Encoding UTF8 -Raw

# ---- Safety check: delimiter must not appear in the HTML -----------------------
if ($html -match '\)rawhtml"') {
    Write-Error 'The HTML content contains the raw string delimiter ")rawhtml" - choose a different delimiter.'
    exit 1
}

# ---- Build header content using string concatenation (avoids here-string quoting issues) ----
$open  = 'R"rawhtml('
$close = ')rawhtml";'

$lines = @(
    '#pragma once'
    '#include <pgmspace.h>'
    ''
    '// Serial Controller live monitor UI - embedded in flash (PROGMEM).'
    '//'
    '// Source: Template/src/main/resources/public/index.html (Java reference implementation).'
    '// The HTML is self-contained (all CSS and JS inline, no external assets) and connects'
    '// to ws://<host>/ws/data to drive the live monitor UI.'
    '//'
    '// *** DO NOT EDIT THIS FILE BY HAND ***'
    '// Regenerate from the Java template with:'
    '//   .\generate_index_html.ps1'
    '//'
    '// Java equivalent: Javalin serves index.html as a classpath static resource at GET /.'
    '// On ESP32 it is stored in flash and served via send_P() in Server.cpp handleRoot().'
    "static const char INDEX_HTML[] PROGMEM = $open"
    $html.TrimEnd()
    $close
)

$content = $lines -join "`n"

# ---- Write output (UTF-8 without BOM) ------------------------------------------
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($headerDst, $content, $utf8NoBom)

$sizeKb = [math]::Round((Get-Item $headerDst).Length / 1024, 1)
Write-Host "Written: $headerDst  ($sizeKb KB)"
